[package]
name = "xtop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.18.0"
winit = { version = "0.29.4", features = ["rwh_05"] }
env_logger = "0.10"
log = "0.4"
pollster = "0.3"
sysinfo = "0.30.0"
bytemuck = { version = "1.14.0", features = [ "derive" ] }
cgmath = "0.18"
anyhow = "1.0.76"
image = "0.25.2"