[package]
name = "lolitop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "22.1.0"
winit = { version = "0.30.5"}
wayland-cursor = "0.31.6"
env_logger = "0.11.5"
log = "0.4.22"
pollster = "0.3"
sysinfo = "0.30.0"
bytemuck = { version = "1.17.1", features = [ "derive" ] }
cgmath = "0.18"
anyhow = "1.0.86"
image = "0.25.2"